services:
  postgres:
    image: postgres:16
    container_name: quizzy_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: quizzy_user
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: quizzy_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
